version: '3.8'

services:
  vibe-coder-host:
    build:
      context: .
      dockerfile: packages/host/Dockerfile
      target: builder  # Use builder stage for development
    container_name: vibe-coder-host-dev
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/app/workspace
      - ~/.claude:/app/.claude:ro
      - ./packages/host/src:/app/packages/host/src  # Mount source for live reload
    environment:
      - NODE_ENV=development
      - SIGNALING_SERVER_URL=${SIGNALING_SERVER_URL:-https://vibe-coder.space/api/signal}
      - SESSION_SECRET=${SESSION_SECRET:-development-secret-key-for-testing-minimum-32-characters-required}
      - MAX_CONCURRENT_SESSIONS=5
      - COMMAND_TIMEOUT=30000
      - ENABLE_SECURITY=true
      - LOG_LEVEL=debug
      - DEBUG=vibe-coder:*
    restart: unless-stopped
    command: ["npm", "run", "dev"]  # Use development command
    user: "${HOST_UID}:${HOST_GID}"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s