version: '3.8'

services:
  vibe-coder-host:
    image: jl1nie/vibe-coder:latest
    container_name: vibe-coder-host
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/app/workspace
      - ~/.claude:/app/.claude:ro
    environment:
      - NODE_ENV=production
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - SIGNALING_SERVER_URL=${SIGNALING_SERVER_URL:-https://signal.vibe-coder.space}
      - DEBUG=${DEBUG:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s