version: '3.8'

services:
  vibe-coder-host:
    build:
      context: .
      dockerfile: packages/host/Dockerfile
      args:
        HOST_UID: ${HOST_UID:-1001}
        HOST_GID: ${HOST_GID:-1001}
    container_name: vibe-coder-host
    ports:
      - "8080:8080"
    volumes:
      - ./workspace:/app/workspace
      - ~/.claude:/app/.claude
    environment:
      - NODE_ENV=production
      - SIGNALING_SERVER_URL=${SIGNALING_SERVER_URL:-https://vibe-coder.space/api/signal}
      - SESSION_SECRET=${SESSION_SECRET}
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-10}
      - COMMAND_TIMEOUT=${COMMAND_TIMEOUT:-30000}
      - ENABLE_SECURITY=${ENABLE_SECURITY:-true}
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - DEBUG=${DEBUG:-}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s