version: '3.8'

services:
  # Development environment
  dev:
    build:
      context: .
      dockerfile: docker/development/Dockerfile
    volumes:
      - .:/workspace
      - /workspace/node_modules
      - ~/.gitconfig:/home/developer/.gitconfig:ro
      - ~/.ssh:/home/developer/.ssh:ro
    ports:
      - "3000:3000"   # PWA dev server
      - "3001:3001"   # Host dev server
      - "5173:5173"   # Vite dev server
      - "8080:8080"   # Signaling server
    environment:
      - NODE_ENV=development
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
    networks:
      - vibe-coder-network
    stdin_open: true
    tty: true
    command: bash

  # Host server for production
  host:
    build:
      context: .
      dockerfile: docker/host/Dockerfile
    container_name: vibe-coder-host
    volumes:
      - workspace_data:/app/workspace
      - session_data:/app/sessions
      - log_data:/app/logs
    ports:
      - "8080:8080"
    environment:
      # Core configuration
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      
      # Claude API (required)
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - CLAUDE_MODEL=${CLAUDE_MODEL:-claude-3-sonnet-20240229}
      - CLAUDE_MAX_TOKENS=${CLAUDE_MAX_TOKENS:-4096}
      
      # Workspace configuration
      - WORKSPACE_DIR=/app/workspace
      - MAX_WORKSPACE_SIZE=${MAX_WORKSPACE_SIZE:-1073741824} # 1GB
      
      # Security settings
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000} # 15 minutes
      - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}
      - MAX_COMMAND_LENGTH=${MAX_COMMAND_LENGTH:-2000}
      - COMMAND_TIMEOUT_MS=${COMMAND_TIMEOUT_MS:-120000} # 2 minutes
      
      # CORS settings
      - CORS_ORIGINS=${CORS_ORIGINS:-http://localhost:3000,https://vibe-coder.space}
      
      # Logging
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_FORMAT=${LOG_FORMAT:-json}
      
      # Session management
      - MAX_CONCURRENT_SESSIONS=${MAX_CONCURRENT_SESSIONS:-10}
      - SESSION_CLEANUP_INTERVAL_MS=${SESSION_CLEANUP_INTERVAL_MS:-300000} # 5 minutes
      
      # WebRTC signaling
      - SIGNALING_SERVER_URL=${SIGNALING_SERVER_URL:-https://vibe-coder-signaling.vercel.app}
      - ICE_SERVERS=${ICE_SERVERS:-[{"urls":"stun:stun.l.google.com:19302"}]}
      
    networks:
      - vibe-coder-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETGID
      - SETUID

  # Redis for signaling server
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - vibe-coder-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    security_opt:
      - no-new-privileges:true

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - host
    networks:
      - vibe-coder-network
    restart: unless-stopped

networks:
  vibe-coder-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  workspace_data:
    driver: local
  session_data:
    driver: local
  log_data:
    driver: local