packages:
  - 'packages/*'
  - 'apps/*'
  - 'tools/*'

catalog:
  # === Core Languages & Runtimes ===
  typescript: ^5.4.2
  '@types/node': ^20.11.0
  tsx: ^4.7.0
  node: '>=20.0.0'
  
  # === React Ecosystem ===
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  react-router-dom: ^6.22.0
  
  # === Build Tools ===
  vite: ^5.1.4
  '@vitejs/plugin-react': ^4.2.1
  vite-plugin-pwa: ^0.19.8
  postcss: ^8.4.35
  autoprefixer: ^10.4.18
  
  # === Testing Framework ===
  vitest: ^1.4.0
  '@testing-library/react': ^14.2.1
  '@testing-library/jest-dom': ^6.4.2
  '@testing-library/user-event': ^14.5.2
  '@playwright/test': ^1.42.1
  playwright: ^1.42.1
  jsdom: ^24.0.0
  supertest: ^6.3.4
  '@types/supertest': ^6.0.2
  
  # === Linting & Formatting ===
  eslint: ^8.57.0
  '@typescript-eslint/eslint-plugin': ^7.0.0
  '@typescript-eslint/parser': ^7.0.0
  eslint-config-prettier: ^9.1.0
  eslint-plugin-prettier: ^5.1.3
  eslint-plugin-react: ^7.34.0
  eslint-plugin-react-hooks: ^4.6.0
  eslint-plugin-security: ^3.0.0
  prettier: ^3.2.5
  
  # === UI Libraries ===
  clsx: ^2.1.0
  tailwindcss: ^3.4.1
  '@tailwindcss/forms': ^0.5.7
  lucide-react: ^0.356.0
  framer-motion: ^11.0.8
  
  # === Server Framework ===
  express: ^4.18.3
  '@types/express': ^4.17.21
  cors: ^2.8.5
  '@types/cors': ^2.8.17
  compression: ^1.7.4
  '@types/compression': ^1.7.5
  
  # === WebRTC & Communication ===
  simple-peer: ^9.11.1
  '@types/simple-peer': ^9.11.8
  ws: ^8.16.0
  '@types/ws': ^8.5.10
  
  # === Security ===
  helmet: ^7.1.0
  express-rate-limit: ^7.2.0
  express-validator: ^7.0.1
  
  # === Utilities ===
  zod: ^3.22.4
  uuid: ^9.0.1
  '@types/uuid': ^9.0.8
  dotenv: ^16.4.5
  
  # === Logging ===
  winston: ^3.11.0
  pino: ^8.17.2
  pino-pretty: ^10.3.1
  
  # === File System ===
  chokidar: ^3.5.3
  
  # === Special Dependencies ===
  wrtc: ^0.4.7
  node-pty: ^1.0.0
  tsc-alias: ^1.8.8
  
  # === Vercel Platform ===
  '@vercel/kv': ^1.0.1
  '@vercel/postgres': ^0.5.1
  '@vercel/node': ^3.0.24
  jose: ^5.2.0
  
  # === PWA & Web APIs ===
  react-use: ^17.5.0
  workbox-window: ^7.0.0
  idb: ^8.0.0
  
  # === Development Tools ===
  serve: ^14.2.1
  http-server: ^14.1.1
  chrome-launcher: ^1.2.0
  lighthouse: ^12.7.1
  axe-core: ^4.10.3
  
