packages:
  - 'packages/*'
  - 'apps/*'
  - 'tools/*'

catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  '@types/react': ^18.2.0
  '@types/react-dom': ^18.2.0
  
  # Build tools
  vite: ^5.1.0
  '@vitejs/plugin-react': ^4.2.0
  
  # Testing
  vitest: ^1.4.0
  '@testing-library/react': ^14.2.0
  '@testing-library/jest-dom': ^6.4.0
  playwright: ^1.42.0
  
  # Utilities
  clsx: ^2.1.0
  tailwindcss: ^3.4.0
  '@tailwindcss/forms': ^0.5.7
  
  # WebRTC
  simple-peer: ^9.11.1
  '@types/simple-peer': ^9.11.8
  
  # Security
  helmet: ^7.1.0
  express-rate-limit: ^7.2.0
  
  # Node.js
  '@types/node': ^20.11.0
  tsx: ^4.7.0